//
//  JXAlertInfoDefinition.h
//  ECTECTIphone
//
//  Created by mac on 15/5/19.
//
//

#ifndef ECTECTIphone_JXAlertInfoDefinition_h
#define ECTECTIphone_JXAlertInfoDefinition_h

#define mLoginingMsg                 @"正在登录..."
#define mCommitingMsg                @"正在提交..."
#define mReviseMsg                   @"正在修改..."
#define mReviseSucceedMsg            @"修改成功"
#define mCommitSucceedMsg            @"提交成功..."
#define mLogoutingMsg                @"正在注销..."
#define mRegisterMsg                 @"正在注册..."
#define mLogoutSucceedMsg            @"注销成功..."
#define mVerificationSucceedMsg      @"验证成功..."
#define mLoginFirstMsg               @"请先登录..."
#define mUploadPictureMsg            @"正在上传..."
#define mInputPhoneNumberErrMsg      @"输入手机号有误"
#define mInputMailAddressErrMsg      @"输入邮箱格式有误"
#define mMailLengthError             @"邮箱长度必须在60位以内"
#define mCheckNewVersionMsg          @"正在检查新版本..."
#define mInputVerifiCodeMsg          @"请先输入验证码"
#define mSameWithLastNumberMsg       @"与当前绑定手机号码一致"
#define mLoadingDataMsg              @"正在努力加载数据..."
#define mLoadingDataErrorMsg         @"加载数据失败"
#define mPasswordNotMatchMsg         @"两次密码输入不一致"
#define mLoginInputErrMsg            @"用户名或密码输入不正确"
#define mInputFeedbackMsg            @"请输入您的反馈意见..."
#define mInputEmailPhoneNumberErrorMsg @"您输入的联系方式有误..."
#define mPhoneNumberInputWrongMsg    @"手机号码输入有误"
#define mLoadingVerificationCodeMsg  @"正在获取验证码"
#define mPassWordInputFormatWrongMsg @"密码输入格式为6-20位"
#define mpassWordInputFormatPayMsg   @"支付密码必须为6位"
#define mVerInputFormat              @"验证码格式为4位"
#define mUserInputFormatWrongMsg     @"帐号不能为空"
#define mPassWordCanNoteNull         @"密码不能为空"
#define mNoDataErrMsg                @"当前未加载到任何数据"
#define mRegisterInputErrMsg         @"请完善注册信息"
#define mNoCommitPasswordMsg         @"请提交新密码"
#define mNoVerificationCodeMsg       @"请输入验证码"
#define mNumberErrMsg                @"必须是数字"
#define mCantOpenCameraMsg           @"该设备不支持拍照"
#define mChangePasswordSucceedMsg    @"密码修改成功"
#define mNotNetWorkMsg               @"网络异常,请确认是否联网"
#define mSendVer                     @"已发送验证码到手机!"
#define mSendMailVer                 @"已发送验证码到邮箱!"
#define m_Verify                     @"正在验证....."
#define m_payVerify                  @"正在验证支付密码...."
#define m_LoseTitle                  @"找回密码"
#define m_RevisePass                 @"修改支付密码"
#define mShouldAgreeProtocal         @"请勾选用户协议"
#define mSetUpPasswordSucceedMsg     @"密码设置成功"
#define mCardID                      @"请输入您的证件号码"
#define mBindMail                    @"邮箱绑定成功"
#define mSettingPay                  @"正在设置支付密码..."
#define mBinding                     @"正在绑定..."
#define mNewPasswordNotMatchMsg      @"两次新密码输入不一致"
#define mCodeStrengthMsg             @"密码强度太低，必须包含数字和字母"
#define mPhoneNumberNotNull          @"手机号不能为空"
#define mCardNumber                  @"身份证号码格式不对"
#define mGetVerifyCodeMsg            @"正在获取验证码..."
#define mGetGatherMsg                @"正在收款..."
#define mRejectMsg                   @"正在拒绝..."
#endif
